namespace PLCrashUtil.Models
{
    /// <summary>
    /// Supported text output formats.
    /// </summary>
    public enum PLCrashReportTextFormat
    {
        /// <summary>
        /// An iOS-compatible crash log text format. Compatible with the crash logs generated by the device and available
        /// through iTunes Connect.
        /// </summary>
        PLCrashReportTextFormatiOS = 0
    }
} 